/*
 Regex
*/

const expression = "/b" + searchterm + "/b";

/* 

http://localhost:3000/agents_api/search?qry=1%C2%A7details~$regex~commercial|literary

this looks for anything that contains literary or commercial 

http://localhost:3000/agents_api/search?qry=1%C2%A7details~$regex~(?i)commercial|literary

case insensitive version

*/

const odd = {
    "$or":
        [
            { "details": { "$regex": "commercial" } },
            { "address": { "$regex": "Road" } }
        ]
}


const marmol = {
    "$or": 
    [
        { "details": { "$regex": "commercial" } },
        { "address": { "$regex": "Road" } }
    ]
}
//this is the version generated by the code which creates an and

const even = {
    "$or":
        [
            { "details": { "$regex": "commercial" } },
            { "address": { "$regex": "Road" } }
        ]
}

const andAND = {
    "details": { "$regex": "commercial" },
    "address": { "$regex": "Road" }
}

const prime = {
    "$or":
        [
            {
                "details": { "$regex": "commercial" },
                "address": { "$regex": "Road" }
            }
        ]
}

const new2 = {
    "$or":
        [
            { "details": { "$regex": "(?i)commercial" } },
            { "address": { "$regex": "Road" } }
        ]
}
const newPrimt = [
    { "details": { "$regex": "(?i)commercial" } },
    { "address": { "$regex": "Road" } }
]